<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>true</IsPackable>
        <PackageId>SyncCronA.Extensions</PackageId>
        <Authors>Rinker-Informatik</Authors>
        <Description>.NET extension for registering application handlers with SyncCronA through gRPC.</Description>
        <PackageTags>SyncCronA;application-agent;gRPC</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Rinker-Informatik/SyncCronA.Extensions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Rinker-Informatik/SyncCronA.Extensions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Google.Protobuf" Version="3.28.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.64.0"/>
        <PackageReference Include="SyncCronA.Contracts" Version="0.0.1-rc.1" />
    </ItemGroup>

    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
